### ISSUE TITLE
Error when trying to drag Spook into Skid Visualizer

### ISSUE THREAD

**Issue by WhatATopic** [LPK-Matt/SkidSuite2#1]
I was trying to open a mapped spook that I mapped with the Jar Correlator but the same error shows up without it being mapped just with a different arrayindexoutofbounds. Instead of 114 > 113, it does 96 > 95.

The version of spook I used was the one linked here.
https://hentaiandecchi.ayzhin.com/forums/showthread.php?tid=2036

Here is the error:

java.lang.ArrayIndexOutOfBoundsException: 114 > 113
        at java.util.Vector.insertElementAt(Unknown Source)
        at javax.swing.tree.DefaultMutableTreeNode.insert(Unknown Source)
        at me.lpk.util.SwingUtils.sort(Unknown Source)
        at me.lpk.util.SwingUtils.sort(Unknown Source)
        at me.lpk.util.SwingUtils.sort(Unknown Source)
        at me.lpk.gui.component.DecompilePanel.openJar(Unknown Source)
        at me.lpk.gui.component.DecompilePanel$1.drop(Unknown Source)
        at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(Unknown Source)
        at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(Unknown Source)
        at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(Unknown Source)
        at sun.awt.dnd.SunDropTargetEvent.dispatch(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processDropTargetEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by LPK-Matt** [comment]
Fixed in most [recent push](https://github.com/LPK-Matt/SkidSuite2/commit/ef9f672e54af9048217826d3d6d79751e32f91c2).
